sudo: required
services:
    - docker
language: go
go:
  - 1.14.x
arch:
  - amd64
  - ppc64le
env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
script:
 - make test
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
    make flannel-git;
    fi
notifications:
  email: false
